import { Video } from "../types/models";

const animated_shorts: Video[] = [
  {
    title: "有关星空的寓言集•其一",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1EM4y1h7Vm/",
    needed: true,
  },
  {
    title: "仙舟通鉴•帝弓七天将",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV19o4y1x7tX/",
    needed: true,
  },
  {
    title: "飞光",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV16g4y157Zc/",
    needed: true,
  },
  {
    title: "耶佩拉叛乱：第47场",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1Nu411H7C6/",
    needed: true,
  },
  {
    title: "仙舟通鉴•五龙远徙",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1nu4y1D7Ex/",
    needed: true,
  },
  {
    title: "玄黄",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1Th4y1S7KF/",
    needed: true,
  },
  {
    title: "云骑武经•说剑",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV12N4y1o7ET/",
    needed: false,
  },
  {
    title: "星际和平导览：甄选、规划和机遇",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1ny4y1P7SN/",
    needed: true,
  },
  {
    title: "绥园伏鬼记",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1Xw411K7Mg/",
    needed: false,
  },
  {
    title: "阮声落华裳，梅出似点妆",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1pb4y1V7Qw/",
    needed: false,
  },
  {
    title: "永火一夜：第33场",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1UK411e7tY/",
    needed: true,
  },
  {
    title: "滴答！一起来梦游吧！",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1iC4y1C7KV/",
    needed: false,
  },
  {
    title: "旧梦重温",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1FZ421z7PE/",
    needed: false,
  },
  {
    title: "《花火》：幕后纪录",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1cC411W7pH/",
    needed: false,
  },
  {
    title: "永劫轮舞",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1aC411h7e6/",
    needed: true,
  },
  {
    title: "虚谭•浮世三千一刀缭断",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV16m411R78H/",
    needed: false,
  },
  {
    title: "假若有一双翅膀",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1wz421U7LZ/",
    needed: false,
  },
  {
    title: "此刻，在同一片星空下",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV16s421u7NP/",
    needed: true,
  },
  {
    title: "格拉默的余烬",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1us421u7sp/",
    needed: true,
  },
  {
    title: "塔塔洛夫向你致意",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1fx4y147PH/",
    needed: false,
  },
  {
    title: "石心誓环•天平两端",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1xE4m1R78a/",
    needed: false,
  },
  {
    title: "天干剑燥，小心火炉",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1xi421a7mg/",
    needed: false,
  },
  {
    title: "飞镝追星",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1TT421z7e3/",
    needed: false,
  },
  {
    title: "清闲自在身",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1WvpTekEPQ/",
    needed: false,
  },
  {
    title: "银河忍法帖•乱武驱魔破邪斩月之卷",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV13pyPYSEar/",
    needed: false,
  },
  {
    title: "太阳落下之后",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1ZBzhYREVs/",
    needed: false,
  },
  {
    title: "不似一片浮云",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV12xkMYjEio/",
    needed: false,
  },
  {
    title: "群星静默如谜",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1dCr3YqEtT/",
    needed: false,
  },
  {
    title: "大 黑 塔 的 魔 法 厨 房",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1cErqYDEGC/",
    needed: false,
  },
  {
    title: "翁法罗斯英雄纪",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1GeUUYREXy/",
    needed: true,
  },
  {
    title: "论泰坦与地上万邦",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1uf6tYBEWN/",
    needed: true,
  },
  {
    title: "诸神尽喑之歌",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1KbcNepEzt/",
    needed: true,
  },
  {
    title: "命运的第一个黎明",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1sZAnevEsh/",
    needed: true,
  },
  {
    title: "那安息的长夜",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV16io9YTEqH/",
    needed: true,
  },
  {
    title: "生命从夜中醒来",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV18hZ1YaEuM/",
    needed: true,
  },
  {
    title: "有关星空的寓言集•其二",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1HsKbznEZg/",
    needed: true,
  },
  {
    title: "听！狂欢在那神佑的山巅",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1twgSzhEo8/",
    needed: true,
  },
  {
    title: "开拓者",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV19RhAzcEdU/",
    needed: false,
  },
  {
    title: "亲爱的三月七",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1uopiz8E9B/",
    needed: false,
  },
  {
    title: "跋涉",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV1BpJrz7EUL/",
    needed: true,
  },
  {
    title: "翁法罗斯英雄纪",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1R5JyzJE9Y/",
    needed: true,
  },
  {
    title: "故事之外：第8场",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1xzs1zDEFi/",
    needed: true,
  },
  {
    title: "再见，昔涟",
    genre: "千星纪游",
    url: "https://www.bilibili.com/video/BV1yXyaBGEVR/",
    needed: false,
  },
  {
    title: "你好，世界",
    genre: "动画短片",
    url: "https://www.bilibili.com/video/BV14G1kB5Evp/",
    needed: true,
  },
];

export default animated_shorts;
