export const fractions: { [key: string]: { name: string } } = {
    stellaron_hunters: { name: "星核猎手" },
    astral_express: { name: "星穹列车" },
    herta_space_station: { name: "黑塔空间站" },
    genius_society: { name: "天才俱乐部" },
    aeon: { name: "星神" },
    garden_of_recollection: { name: "流光忆庭" },
    belobog: { name: "贝洛伯格" },
    masked_fools: { name: "假面愚者" },
    xianzhou_alliance: { name: "仙舟联盟" },
    lord_ravager: { name: "绝灭大君" },
    interastral_peace_appliances: { name: "星际和平公司" },
    penacony: { name: "匹诺康尼" },
    intelligentsia_guild: { name: "博识学会" },
    knights_of_beauty: { name: "纯美骑士团" },
    self_annihilators: { name: "自灭者" },
    galaxy_rangers: { name: "巡海游侠" },
    the_cremators: { name: "焚化工" },
    amphoreus: { name: "翁法罗斯" },
    unknown: { name: "未知阵营" },
};
